name: CI – build & push

on:
  push:
    branches: [ master ]
    tags:     [ 'v*' ]

env:
  IMAGE_NAME: cybersec007/django-demo      # ваше имя репо в Docker Hub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Decide image tag
      id: vars
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
        else
          echo "tag=${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"
        fi

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
