name: CI — build & push

on:
  push:
    branches: [ master ]           # пуши в master вызывают CI
    tags:     [ 'v*' ]             # а ещё можно пушить теги v1.2.3

env:
  REGISTRY: docker.io              # 👈 удобно вынести сюда
  IMAGE_NAME: cybersec7007/django-demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # высчитываем тег:
      - name: Decide image tag
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}"   >>"$GITHUB_OUTPUT"
          else
            echo "tag=${GITHUB_SHA::8}"           >>"$GITHUB_OUTPUT"
          fi

      # логинимся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # билдим и пушим
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
